name: "Setup Frontend Dependencies"
description: "Sets up the frontend dependencies required for the testing containers."

runs:
  using: "composite"
  steps:
    - name: Set up node LTS
      uses: actions/setup-node@v4
      with:
        node-version: "lts"
    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ./frontend
