name: Run Algorithm Unit Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  build:
    name: Algorithm CI Testing

    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository
      uses: actions/checkout@v2

    - name: Set up Python (latest)
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Test algorithm with pytest
      run: |
        cd backend
        python3 -m pytest algorithms