name: Run Algorithm Unit Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ adam/continuous-integration, dev, main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Check out repository code
    - uses: actions/checkout@v2

    - name: Set up Python (latest)
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Test algorithm with pytest
      run: |
        cd backend
        python3 -m pytest algorithms