name: Docker
on:
  push:
    branches:
      - "dev"

jobs:
  build:
    name: "Build (${{ matrix.component }})"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend]
        include:
          - component: frontend
            dockerfile: production.dockerfile
            args: |
              "API_URL=https://circlesapi.csesoc.unsw.edu.au"
          - component: backend
            dockerfile: backend.dockerfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.component }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: ${{ matrix.component }}/${{ matrix.dockerfile }}
          build-args: ${{ matrix.args }}
          tags: |
            ghcr.io/csesoc/circles-${{ matrix.component }}:${{ github.sha }}
            ghcr.io/csesoc/circles-${{ matrix.component }}:latest
          labels: ${{ steps.meta.outputs.labels }}
