name: ESLint

on:
  pull_request:
    branches: [dev, main]

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      
      - name: Install Node.js dependencies
        run: cd frontend && npm ci

      - name: Run linters
        run: npm run lint
