name: ESLint

on:
  pull_request:
    branches: [dev, main]

jobs:
  run-linter:
    name: Run linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
