name: Pylint
# ---------------------------------------#
# ---------------------------------------#
# ---   PYLINTER - Github Actions   -----#
# ---------------------------------------#
# ---------------------------------------#
# Pylint for github actions. Runs seperate to superlinter

# Documentation and source:
# https://github.com/cclauss/GitHub-Action-for-pylint



on:
  pull_request:
    branches: [dev, main]

jobs:
  build:
    name: Pylint
    # Works on most linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with: 
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

      env:
        # may be worth changing this to master / main in future
        DEFAULT_BRANCH: dev
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # For pylint's settings
        PYTHON_PYLINT_CONFIG_FILE: .pylintrc
