# ---------------------------------------#
# ---------------------------------------#
# --- SUPER LINTER - Github Actions -----#
# ---------------------------------------#
# ---------------------------------------#
# NOTE: State of this linter:
# This is the one that is multi-lingual. It is currently turned off in favour
# of `pylint` for python files. If at any point, you would like to lint
# anything from a different language, uncomment everything below this comment
# and place the file extension in the path

# name: Lint Code Base
# #
# # Documentation:
# # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# #
# # Find super linter at:
# # https://github.com/github/super-linter

# on:
#   push:
#     paths:
#       # Add specific files / filetypes here.
#       # Use `**` to wildcard through multiply paths
#       - "**.py"
#     # [un]-comment the following line to toggle for push to master
#     # branches-ignore: [master, main]

#   # This will only work when this workflow is on default branch
#   # TODO Uncomment when merging
#   # pull_requests:
#   #   branches: [dev, master, main]

# jobs:
#   build:
#     name: Lint Code Base
#     # Works on most linux
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
#         with:
#           # Do not change this number. Full depth needed to filter changed
#           # files
#           fetch-depth: 0

#       # Actually run the linter
#       - name: Lint Code Base
#         uses: github/super-linter@v4
#         env:
#           # false := lint only the files that have changes
#           VALIDATE_ALL_CODEBASE: false
#           # may be worth changing this to master / main
#           DEFAULT_BRANCH: dev
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           # For pylint's settings
#           PYTHON_PYLINT_CONFIG_FILE: .pylintrc
